### ISSUE TITLE
Very Close to what i was looking for but

### ISSUE THREAD

**Issue by somesh101** [K4P11/GUI-for-EWBF#3]
Pro:
Does what it says. 

con's
Poorly written other's will have hard tome to wrap their head around it specially noob people like me. 
Fixed urls-- not everyone wants tos price in euro.
No avg values.... just plotting graph. 
lastly constant time period. that i don't feel is correct upto the mark. 
limited option for graphs.

**Comment by K4P11** [comment]
1. Yes, it is indeed poorly written and is mostly due to laziness

2. The price was not the main point of the GUI and I added support for USD

3. There is average value for total speed, I will look into this if there is a easy way to implement it. BTW in long run (let's say 24 h) you will be able to see pretty well the AVG value. In addition, the graphs have built in menu which opens with right click that allows downsampling than can be used for example to show moving average in graph, in other terms, the average.

4. Constant time period for updating the main GUI window is due the fact there is not much to show as minimum interval for anything visible to happen is 30 s. Other reason for main window constant update interval is that I do not want anyone to get banned from sites for using this GUI and inserting too fast interval. The graphing interval can be adjusted in seconds, though, as said under 30 s is not wise and to have any real impact graphing n*30 s interval should be used.

**Comment by somesh101** [comment]
1 : it's not from lziness... i am still a noob i have to check everything before actully putting it in code. 
    Though i will improve it.

2 : You hardcoded the USD or EUR better way to get it from json.
3: i checked the program for hours a nd when i looked at avg value it flaactued alot... like 2-3 sols with each update from ewbf. 
3: i am not saying to obtain any values from sites per sec only the data from ewbf miner.

**Comment by K4P11** [comment]
1. To clarify it is due to my laziness as i made it with the way that came up to my mind first

2. yes in fact there is with some list manipulation and QT combo box this can be done with wider cash support. Other possibilities is string manipulation, but in this case i think the list way is easier.

3. I am unable to reproduce this kind of behavior. Do you have high fluctuation in mining speed? My fluctuation with 2x GTX 1070 is around 10 Sol/s per update and AVG will have fluctuation of 0-1. Larger amount of GPUs will produce higher deviation and thus increase the fluctuation in AVG value. For example I'm having speed of around 960 Sol/s so 1-2 Sol/s fluctuation is not much.

4. Maybe I'm missing the point of this. You are able to modify the sampling time from miner by increasing or decreasing the value in Monitor update interval box from 30 s. just type in the wanted interval.

**Comment by K4P11** [comment]
2. Done

**Comment by somesh101** [comment]
ohkay here is what i am thinking... 
i want to measure how much money per share i am making ... on an avg how many solution per hour or so i am doing.
how much i am deviating from optimal value. that can not be done via http in ewbf. the reson i don't want to use time based sampling. that kills all my goals. i want to buffer or split the output from the ewbf.  

i have 10-15 sols flucations at max. but on avg 5-8.

**Comment by somesh101** [comment]
graph not showin up in th current version.
and also display max and min sols.

**Comment by K4P11** [comment]
Odd for me it works, Could you be more specific? Only thing I did, was change the ticks from qtime to time library to show datetime on graphs.

**Comment by K4P11** [comment]
![image](https://user-images.githubusercontent.com/30934842/29368729-421bae52-82a9-11e7-9432-79ecd4d4164a.png)
Anyways, I compiled it again and changed the file in release

**Comment by somesh101** [comment]
1: it's bad idea put your conf in there
2: tags: gpu0 and gpu1 are overlapped by colour indicator and are way in  mid of graph
3: Show them only once in entire graph screen. 
4: put the avg value at gui window and at graph. may be just put the value in parnthesis in title like 
efficiency(3.00)

**Comment by somesh101** [comment]
5th: No ouput n graph window
did you change anything how the graph will get it's values.
coz i am not using it to start miner. my miner is already running.

can you put some comments in your code. specaily where you have used arbitarryr variable names

**Comment by K4P11** [comment]
1. It was accidentally there as i forgot to delete it :)
5. Think i fixed it as it seemed to be problem with acquiring the information with json. In error case the initialization was interrupted and resulted in black window. Now it should at least give a graph, but if there is problem with url (double check it)nothing is show, It will try to initialize the graph during every update, if there is data available. Though, to update the window, it needs to be closed and re-opened.

**Comment by K4P11** [comment]
Lines: 228-331 were reason for black screen as said earlier the initialization were not finished.
```
try:
            l= requests.get(url).json()
except requests.exceptions.RequestException as e:
            return
```

**Comment by somesh101** [comment]
still no comments. Good

**Comment by K4P11** [comment]
You got the graphs now?

**Comment by somesh101** [comment]
lolz
